# Generated by Django 3.1.2 on 2020-10-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='Parking',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('in_future', 'In_Future')], default='yes', max_length=20),
        ),
        migrations.AlterField(
            model_name='buy',
            name='Playground',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('in_future', 'In_Future')], default='yes', max_length=20),
        ),
    ]
