# Generated by Django 3.1.2 on 2020-10-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_rent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Owner_name', models.CharField(max_length=20)),
                ('Contact', models.IntegerField()),
                ('Property', models.CharField(choices=[('private', 'Private'), ('government', 'Government')], default='private', max_length=20)),
                ('Property_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'commercial'), ('forest', 'Forest'), ('garden', 'Garden'), ('appartments', 'Appartments'), ('other', 'other')], default='other', max_length=20)),
                ('Price', models.FloatField()),
                ('Area', models.FloatField()),
                ('Description', models.TextField()),
                ('Document', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=20)),
                ('Tax_Raciept', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=20)),
                ('Survey_Sketch', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=20)),
                ('Pincode', models.IntegerField()),
                ('State', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=20)),
                ('Address', models.TextField()),
                ('Img1', models.ImageField(upload_to='img/')),
                ('Date', models.DateField()),
            ],
        ),
    ]
