# Generated by Django 3.1.2 on 2020-10-16 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_land'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Agent_name', models.CharField(max_length=20)),
                ('Contact', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Agent_type', models.CharField(choices=[('buy_Agent', 'Buy_Agent'), ('rent_Agent', 'Rent_Agent'), ('land_Agent', 'Land_Agent')], default='buy_Agent', max_length=10)),
                ('Img1', models.ImageField(upload_to='img/')),
            ],
        ),
    ]
