# Generated by Django 3.1.2 on 2020-10-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_buy_gallary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='gallary',
            field=models.FileField(blank=True, null=True, upload_to='img/'),
        ),
    ]
