# Generated by Django 3.1.2 on 2020-10-19 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_post_postimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='img/')),
                ('buy', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testapp.buy')),
            ],
        ),
    ]
