# Generated by Django 3.1.2 on 2020-10-20 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_auto_20201019_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/')),
            ],
        ),
        migrations.CreateModel(
            name='PostForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('body', models.CharField(max_length=245)),
            ],
        ),
    ]
