# Generated by Django 3.1.2 on 2020-10-20 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0013_imageform_postform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageForm',
            new_name='Image',
        ),
        migrations.RenameModel(
            old_name='PostForm',
            new_name='Post',
        ),
    ]
