# Generated by Django 3.1.2 on 2020-10-20 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0015_auto_20201020_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyimage',
            old_name='Owner_name',
            new_name='name',
        ),
    ]
