# Generated by Django 3.1.2 on 2020-10-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0016_auto_20201020_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyimage',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
