# Generated by Django 3.1.2 on 2020-10-20 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0017_auto_20201020_0923'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuyImage',
        ),
    ]
