# Generated by Django 3.1.2 on 2020-10-20 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0020_auto_20201020_1134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.DeleteModel(
            name='Land',
        ),
        migrations.DeleteModel(
            name='Rent',
        ),
    ]
