# Generated by Django 3.1.2 on 2020-10-20 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0025_property_propertyimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyimage',
            name='images',
        ),
        migrations.RemoveField(
            model_name='buyimage',
            name='name',
        ),
        migrations.AddField(
            model_name='buyimage',
            name='buy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='testapp.buy'),
        ),
        migrations.AddField(
            model_name='buyimage',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
