# Generated by Django 3.1.2 on 2020-10-20 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testapp', '0026_auto_20201020_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyimage',
            name='buy',
        ),
        migrations.RemoveField(
            model_name='buyimage',
            name='image',
        ),
        migrations.AddField(
            model_name='buyimage',
            name='images',
            field=models.FileField(default=1, upload_to='img/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyimage',
            name='name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('rent', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='testapp.rent')),
            ],
        ),
    ]
