# Generated by Django 3.1.2 on 2020-10-20 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0027_auto_20201020_1224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuyImage',
        ),
    ]
