# Generated by Django 3.1.2 on 2020-10-20 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0029_buyimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuyImage',
        ),
    ]
