# Generated by Django 3.1.2 on 2020-10-20 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testapp', '0030_delete_buyimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='property',
        ),
        migrations.AlterField(
            model_name='rent',
            name='Owner_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Owner_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='PropertyImage',
        ),
    ]
