# Generated by Django 3.1.2 on 2020-10-20 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testapp', '0031_auto_20201020_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='Owner_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Owner_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
