# Generated by Django 3.1.2 on 2020-10-20 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testapp', '0032_auto_20201020_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='Owner_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Owner_name1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BuyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('rent', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='testapp.buy')),
            ],
        ),
    ]
