# Generated by Django 3.1.2 on 2020-10-20 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testapp', '0033_auto_20201020_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyimage',
            old_name='rent',
            new_name='buy',
        ),
        migrations.AlterField(
            model_name='land',
            name='Owner_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Owner_name2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LandImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('land', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='testapp.land')),
            ],
        ),
    ]
