# Generated by Django 3.1.2 on 2020-10-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0035_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('date', models.DateField()),
                ('property', models.CharField(max_length=100)),
                ('msg', models.TextField()),
            ],
        ),
    ]
