# Generated by Django 3.1.2 on 2020-10-22 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0036_property'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Property',
            new_name='Select_Property',
        ),
    ]
