# Generated by Django 3.1.2 on 2020-10-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0037_auto_20201022_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='select_property',
            name='Appointment',
            field=models.DateTimeField(null=True),
        ),
    ]
