# Generated by Django 3.1.2 on 2020-10-23 12:53

from django.db import migrations, models
import testapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0041_auto_20201023_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='Contact',
            field=models.CharField(max_length=15, validators=[testapp.validators.validate_phonenumber]),
        ),
    ]
