# Generated by Django 3.1.2 on 2020-10-23 12:57

from django.db import migrations, models
import testapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0042_auto_20201023_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='Contact',
            field=models.CharField(max_length=15, validators=[testapp.validators.validate_phonenumber]),
        ),
        migrations.AlterField(
            model_name='land',
            name='Contact',
            field=models.CharField(max_length=15, validators=[testapp.validators.validate_phonenumber]),
        ),
        migrations.AlterField(
            model_name='rent',
            name='Contact',
            field=models.CharField(max_length=15, validators=[testapp.validators.validate_phonenumber]),
        ),
    ]
