# Generated by Django 3.1.2 on 2020-10-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0043_auto_20201023_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='Agent_type',
            field=models.CharField(choices=[('', 'Select'), ('buy_Agent', 'Buy_Agent'), ('rent_Agent', 'Rent_Agent'), ('land_Agent', 'Land_Agent')], default='select', max_length=10),
        ),
        migrations.AlterField(
            model_name='buy',
            name='Cinema',
            field=models.CharField(choices=[('', 'Select'), ('yes', 'Yes'), ('no', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='buy',
            name='Club',
            field=models.CharField(choices=[('', 'Select'), ('yes', 'Yes'), ('no', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='buy',
            name='Electricity',
            field=models.CharField(choices=[('', 'Select'), ('yes', 'Yes'), ('no', 'No')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='buy',
            name='Fire',
            field=models.CharField(choices=[('', 'Select'), ('yes', 'Yes'), ('no', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='buy',
            name='Gym',
            field=models.CharField(choices=[('', 'Select'), ('yes', 'Yes'), ('no', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='buy',
            name='Hospital',
            field=models.CharField(choices=[('', 'Select'), ('yes', 'Yes'), ('no', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='buy',
            name='Hotel',
            field=models.CharField(choices=[('', 'Select'), ('yes', 'Yes'), ('no', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='buy',
            name='Lift',
            field=models.CharField(choices=[('', 'Select'), ('yes', 'Yes'), ('no', 'No')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='buy',
            name='Living',
            field=models.CharField(choices=[('', 'Select'), ('yes', 'Yes'), ('no', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='buy',
            name='Mall',
            field=models.CharField(choices=[('', 'Select'), ('yes', 'Yes'), ('no', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='buy',
            name='Parking',
            field=models.CharField(choices=[('', 'Select'), ('yes', 'Yes'), ('no', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='buy',
            name='Playground',
            field=models.CharField(choices=[('', 'Select'), ('yes', 'Yes'), ('no', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='buy',
            name='Poll',
            field=models.CharField(choices=[('', 'Select'), ('yes', 'Yes'), ('no', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='buy',
            name='School',
            field=models.CharField(choices=[('', 'Select'), ('yes', 'Yes'), ('no', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='buy',
            name='Security',
            field=models.CharField(choices=[('', 'Select'), ('yes', 'Yes'), ('no', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='buy',
            name='Temple',
            field=models.CharField(choices=[('', 'Select'), ('yes', 'Yes'), ('no', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='buy',
            name='Type',
            field=models.CharField(choices=[('', 'Select'), ('flat', 'Flat'), ('bunglow', 'Bunglow'), ('shop', 'Shop'), ('office', 'Office')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='buy',
            name='Water',
            field=models.CharField(choices=[('', 'Select'), ('24/7', '24/7'), ('morning', 'Morning'), ('night', 'Night')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='buy',
            name='Wifi',
            field=models.CharField(choices=[('', 'Select'), ('24/7', '24/7'), ('morning', 'Morning'), ('night', 'Night')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='land',
            name='Document',
            field=models.CharField(choices=[('', 'Select'), ('yes', 'Yes'), ('no', 'No')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='land',
            name='Property',
            field=models.CharField(choices=[('', 'Select'), ('private', 'Private'), ('government', 'Government')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='land',
            name='Property_type',
            field=models.CharField(choices=[('', 'Select'), ('residential', 'Residential'), ('commercial', 'commercial'), ('forest', 'Forest'), ('garden', 'Garden'), ('appartments', 'Appartments'), ('other', 'other')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='land',
            name='Survey_Sketch',
            field=models.CharField(choices=[('', 'Select'), ('yes', 'Yes'), ('no', 'No')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='land',
            name='Tax_Raciept',
            field=models.CharField(choices=[('', 'Select'), ('yes', 'Yes'), ('no', 'No')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='rent',
            name='Cinema',
            field=models.CharField(choices=[('', 'Select'), ('yes', 'Yes'), ('no', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='rent',
            name='Club',
            field=models.CharField(choices=[('', 'Select'), ('yes', 'Yes'), ('no', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='rent',
            name='Electricity',
            field=models.CharField(choices=[('', 'Select'), ('yes', 'Yes'), ('no', 'No')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='rent',
            name='Fire',
            field=models.CharField(choices=[('', 'Select'), ('yes', 'Yes'), ('no', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='rent',
            name='Gym',
            field=models.CharField(choices=[('', 'Select'), ('yes', 'Yes'), ('no', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='rent',
            name='Hospital',
            field=models.CharField(choices=[('', 'Select'), ('yes', 'Yes'), ('no', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='rent',
            name='Hotel',
            field=models.CharField(choices=[('', 'Select'), ('yes', 'Yes'), ('no', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='rent',
            name='Lift',
            field=models.CharField(choices=[('', 'Select'), ('yes', 'Yes'), ('no', 'No')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='rent',
            name='Living',
            field=models.CharField(choices=[('', 'Select'), ('yes', 'Yes'), ('no', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='rent',
            name='Mall',
            field=models.CharField(choices=[('', 'Select'), ('yes', 'Yes'), ('no', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='rent',
            name='Parking',
            field=models.CharField(choices=[('', 'Select'), ('yes', 'Yes'), ('no', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='rent',
            name='Playground',
            field=models.CharField(choices=[('', 'Select'), ('yes', 'Yes'), ('no', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='rent',
            name='Poll',
            field=models.CharField(choices=[('', 'Select'), ('yes', 'Yes'), ('no', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='rent',
            name='Property',
            field=models.CharField(choices=[('', 'Select'), ('residential', 'Residential'), ('commercial', 'commercial')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='rent',
            name='School',
            field=models.CharField(choices=[('', 'Select'), ('yes', 'Yes'), ('no', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='rent',
            name='Security',
            field=models.CharField(choices=[('', 'Select'), ('yes', 'Yes'), ('no', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='rent',
            name='Temple',
            field=models.CharField(choices=[('', 'Select'), ('yes', 'Yes'), ('no', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='rent',
            name='Type',
            field=models.CharField(choices=[('', 'Select'), ('flat', 'Flat'), ('bunglow', 'Bunglow'), ('shop', 'Shop'), ('office', 'Office')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='rent',
            name='Water',
            field=models.CharField(choices=[('', 'Select'), ('24/7', '24/7'), ('morning', 'Morning'), ('night', 'Night')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='rent',
            name='Wifi',
            field=models.CharField(choices=[('', 'Select'), ('24/7', '24/7'), ('morning', 'Morning'), ('night', 'Night')], default='select', max_length=20),
        ),
    ]
