# Generated by Django 3.1.2 on 2020-10-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0044_auto_20201023_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='Wifi',
            field=models.CharField(choices=[('', 'Select'), ('yes', 'Yes'), ('no', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='rent',
            name='Wifi',
            field=models.CharField(choices=[('', 'Select'), ('yes', 'Yes'), ('no', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
    ]
