# Generated by Django 3.1.2 on 2020-10-24 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0046_buy_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='Cinema',
            field=models.CharField(choices=[('', 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='buy',
            name='Club',
            field=models.CharField(choices=[('', 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='buy',
            name='Electricity',
            field=models.CharField(choices=[('', 'Select'), ('Yes', 'Yes'), ('No', 'No')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='buy',
            name='Fire',
            field=models.CharField(choices=[('', 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='buy',
            name='Gym',
            field=models.CharField(choices=[('', 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='buy',
            name='Hospital',
            field=models.CharField(choices=[('', 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='buy',
            name='Hotel',
            field=models.CharField(choices=[('', 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='buy',
            name='Lift',
            field=models.CharField(choices=[('', 'Select'), ('Yes', 'Yes'), ('No', 'No')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='buy',
            name='Living',
            field=models.CharField(choices=[('', 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='buy',
            name='Mall',
            field=models.CharField(choices=[('', 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='buy',
            name='Parking',
            field=models.CharField(choices=[('', 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='buy',
            name='Playground',
            field=models.CharField(choices=[('', 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='buy',
            name='Poll',
            field=models.CharField(choices=[('', 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='buy',
            name='School',
            field=models.CharField(choices=[('', 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='buy',
            name='Security',
            field=models.CharField(choices=[('', 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='buy',
            name='Temple',
            field=models.CharField(choices=[('', 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='buy',
            name='Wifi',
            field=models.CharField(choices=[('', 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='land',
            name='Document',
            field=models.CharField(choices=[('', 'Select'), ('Yes', 'Yes'), ('No', 'No')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='land',
            name='Survey_Sketch',
            field=models.CharField(choices=[('', 'Select'), ('Yes', 'Yes'), ('No', 'No')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='land',
            name='Tax_Raciept',
            field=models.CharField(choices=[('', 'Select'), ('Yes', 'Yes'), ('No', 'No')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='rent',
            name='Cinema',
            field=models.CharField(choices=[('', 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='rent',
            name='Club',
            field=models.CharField(choices=[('', 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='rent',
            name='Electricity',
            field=models.CharField(choices=[('', 'Select'), ('Yes', 'Yes'), ('No', 'No')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='rent',
            name='Fire',
            field=models.CharField(choices=[('', 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='rent',
            name='Gym',
            field=models.CharField(choices=[('', 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='rent',
            name='Hospital',
            field=models.CharField(choices=[('', 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='rent',
            name='Hotel',
            field=models.CharField(choices=[('', 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='rent',
            name='Lift',
            field=models.CharField(choices=[('', 'Select'), ('Yes', 'Yes'), ('No', 'No')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='rent',
            name='Living',
            field=models.CharField(choices=[('', 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='rent',
            name='Mall',
            field=models.CharField(choices=[('', 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='rent',
            name='Parking',
            field=models.CharField(choices=[('', 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='rent',
            name='Playground',
            field=models.CharField(choices=[('', 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='rent',
            name='Poll',
            field=models.CharField(choices=[('', 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='rent',
            name='School',
            field=models.CharField(choices=[('', 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='rent',
            name='Security',
            field=models.CharField(choices=[('', 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='rent',
            name='Temple',
            field=models.CharField(choices=[('', 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
        migrations.AlterField(
            model_name='rent',
            name='Wifi',
            field=models.CharField(choices=[('', 'Select'), ('Yes', 'Yes'), ('No', 'No'), ('in_future', 'In_Future')], default='select', max_length=20),
        ),
    ]
